### ISSUE TITLE
Enlaces a Videos Incorrectos

### ISSUE THREAD

**Issue by canchebagur** [ElectronicCats/inteligent_machines#24]
Hola, detecté que a partir del módulo 7, los videos que están en la página web de Máquinas Inteligentes son incorrectos, [por ejemplo acá](https://maquinasinteligentes.org/#/class/programando_codigo).

**Comment by Arthulisher** [comment]
Hola @canchebagur  Gracias por su feedback en un momento procederemos a corroborar esto.
ElectronicCats agradece su preferencia...

**Comment by jazhe** [comment]
Hola @canchebagur!
Mil disculpas por la demora en la solución de este problema. Los links han sido arreglados.
¡Muchas gracias por esta observación que nos ayuda a mejorar nuestros contenidos!
¡Saludos!

**Comment by jazhe** [comment]
Hola @canchebagur!
¡Muchas gracias por tu paciencia y tus comentarios! Y Una disculpa por la demora en el seguimiento de este issue. Estamos trabajando en la solución de estos errores, te mantendremos actualizado en cuanto lo resolvamos.
Nuvamente, gracias por tu paciencia.
Que tengas un excelente día.

**Comment by sabas1080** [comment]
@canchebagur hemos arreglado los videos solicitados, gracias por notificarnos, un saludos hasta Guatemala
